'use strict';
const assert=require('node:assert/strict'),DB=require('./memory-db'),C=require('../public/company-config');
const db=DB({}),S=require('../api/_supabase'),A=require('../api/_appAuth');let user={role:'owner'};
require.cache[require.resolve('../api/_supabase')].exports={...S,supabaseAdmin:()=>db};
require.cache[require.resolve('../api/_appAuth')].exports={...A,authenticateDesktopRequest:async()=>({user})};
delete require.cache[require.resolve('../api/_recovery')];
const handler=require('../api/companies'),recovery=require('../api/recovery'),cloudHandler=require('../api/backup-cloud'),Cloud=require('../api/_backupCloud'),D=require('../api/_companies');
async function call(fn,method,query={},body){let status=200,data;await fn({method,query,body},{setHeader(){},status(c){status=c;return this},json(d){data=d;}});return {status,data};}
(async()=>{
 assert.equal(A.normalizePermissions(null).manageRecovery,false);
 const png='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jS1sAAAAASUVORK5CYII=';
 const before=JSON.stringify(db.rows);user={role:'employee',companies:['hazeyn'],permissions:{exportBackup:true}};
 assert.equal((await call(handler,'POST',{}, {revision:'',company:{name:'Yetkisiz'}})).status,403);assert.equal(JSON.stringify(db.rows),before);
 assert.equal((await call(recovery,'GET',{company:'hazeyn',action:'export'})).status,403);
 user={role:'owner'};const created=await call(handler,'POST',{}, {revision:'',company:{name:'Deneme Firma',city:'İzmir',logo:png}});assert.equal(created.status,200);
 const company=created.data.companies.find(x=>x.name==='Deneme Firma');assert.match(company.id,/^c_[a-f0-9]{24}$/);assert.notEqual(S.companyRowId(company.id),S.companyRowId('hazeyn'));assert.equal(S.companyDefaultData(company.id).passengerLists.length,0);
 assert.equal((await call(handler,'POST',{}, {revision:'',company:{name:'Çakışma'}})).status,409);
 assert.equal((await call(handler,'POST',{}, {revision:created.data.revision,company:{name:'Deneme Firma',logo:png}})).status,409);
 assert.throws(()=>D.validate({id:'users',name:'Kötü'}));assert.throws(()=>D.validate({name:'Firma',logo:'data:image/svg+xml,<svg/>'}));
 const updated=await call(handler,'POST',{}, {revision:created.data.revision,company:{id:company.id,name:'Deneme Firma',logo:png}});assert.equal(updated.status,200);assert.equal(C.config[company.id].receiptLogo,png);
 const P=require('../public/bus-plan'),BC=require('../public/bus-companies');const plan=P.normalizePlan({buses:[{id:'b',name:'Test',capacity:49,limit:49,rear:5,doorAfter:6,assignments:{},companyRule:{mode:'split',left:company.id,right:'hazeyn',center:'any'}}]});assert.equal(plan.buses[0].companyRule.left,company.id);assert.ok(BC.names[company.id]);
 user={role:'employee',companies:['hazeyn'],permissions:{manageRecovery:true}};
 const full=await call(recovery,'GET',{company:'hazeyn',action:'export'});assert.equal(full.status,200);assert.ok(full.data.records[company.id]);assert.ok(full.data.records.companyDirectory.data.companies.some(x=>x.id===company.id));
 const backup=full.data;
 assert.equal((await call(recovery,'POST',{company:'hazeyn',resource:'companyDirectory',action:'preview'},{backup})).status,403);
 user={role:'owner'};
 const preview=await call(recovery,'POST',{company:'hazeyn',resource:'companyDirectory',action:'preview'},{backup});assert.equal(preview.status,200);
 assert.equal((await call(recovery,'POST',{company:'hazeyn',resource:'companyDirectory',action:'restore'},{backup,revision:preview.data.revision,confirm:true})).status,200);
 assert.equal(C.config[company.id].logo,png);
 const bad=structuredClone(backup);bad.records.companyDirectory.data.companies[0].logo='javascript:alert(1)';bad.sha256=require('../api/_recovery').digest(bad.records);
 assert.equal((await call(recovery,'POST',{company:'hazeyn',resource:'companyDirectory',action:'preview'},{backup:bad})).status,400);
 user={role:'employee',companies:['hazeyn'],permissions:{manageRecovery:true}};
 process.env.BACKUP_TOKEN_ENCRYPTION_KEY='synthetic-test-encryption-key';
 assert.equal((await call(cloudHandler,'POST',{action:'configure',provider:'google'},{clientId:'test-client',clientSecret:'test-secret'})).status,403);
 user={role:'owner'};assert.equal((await call(cloudHandler,'POST',{action:'configure',provider:'google'},{clientId:'test-client',clientSecret:'test-secret'})).status,200);
 assert.ok(!JSON.stringify(db.rows).includes('test-secret'));assert.equal((await Cloud.status(db)).google.configured,true);assert.equal((await Cloud.configured(db,'google')).clientSecret,'test-secret');
 const publicCatalog=await call(handler,'GET');assert.ok(!JSON.stringify(publicCatalog).includes('test-secret'));
 user={role:'employee',permissions:{manageRecovery:false}};assert.equal((await call(recovery,'GET',{company:'hazeyn',action:'export'})).status,403);
 const pdf=await require('../api/_receiptPdf').createReceiptPdf({companyId:company.id,state:{settings:{}},passenger:{name:'Deneme'},payment:{amount:1},tour:{},list:{}});assert.ok(pdf.length>1000);
 C.apply([]);console.log('Company management: isolated IDs, denied writes, conflicts, logos/PDF, dynamic bus sides, delegated/revoked recovery, encrypted provider settings and full export passed.');
})().catch(e=>{console.error(e);process.exitCode=1;});
