const assert = require('node:assert/strict');
const rules = require('../public/document-reader');
const doc = rules.normalize({version:1,documentType:'passport',name:'TEST PERSON',tc:'10000000146',passportNo:'U12345678',passportEnd:'2030-02-28'});
const existing = {id:'original',tc:doc.tc,name:'TEST',phone:'555',passportStart:'2020-01-01',roomPeople:'2',accounting:{payments:[{id:'payment'}]}};
assert.equal(rules.match([existing],doc),existing);
const merged = rules.merge(existing,doc);
assert.equal(rules.merge({...existing,name:'',passportNo:''},doc).name,'TEST PERSON');
assert.equal(merged.name,'TEST PERSON');
assert.equal(merged.id,'original');
assert.equal(merged.passportNo,'U12345678');
assert.equal(merged.passportStart,'2020-01-01');
assert.equal(merged.phone,'555');
assert.equal(merged.roomPeople,'2');
assert.deepEqual(merged.accounting,existing.accounting);
assert.equal(existing.name,'TEST');
assert.equal(rules.match([merged],doc).id,'original');
assert.throws(()=>rules.match([existing,{...existing,id:'duplicate'}],doc),/Birden fazla/);
assert.throws(()=>rules.match([{tc:'different',passportNo:doc.passportNo}],doc),/farklı/);
assert.equal(rules.match([{name:doc.name}],doc),null);
const idDoc=rules.normalize({version:1,documentType:'identity',name:'TEST PERSON',identityNo:'A12345678',passportNo:'WRONG',passportEnd:'2030-01-01'});
assert.equal(idDoc.passportNo,undefined);
assert.equal(rules.merge(merged,idDoc).passportNo,doc.passportNo);
assert.equal(rules.normalize({...doc,version:1,tc:'',birthDate:'2000-02-29'}).birthDate,'2000-02-29');
assert.throws(()=>rules.normalize({...doc,version:1,birthDate:'2001-02-29'}),/tarih/);
assert.throws(()=>rules.normalize({...doc,version:1,tc:'00000000000'}),/T.C./);
assert.throws(()=>rules.normalize({...doc,version:1,tc:'10000000147'}),/T.C./);
assert.throws(()=>rules.normalize({...doc,version:99}),/biçimi/);
assert.throws(()=>rules.normalize({version:1,documentType:'passport',name:'TEST'}),/numarası/);
assert.equal(rules.normalize({...doc,version:1,accounting:{payments:[]},id:'evil'}).accounting,undefined);
console.log('document-reader matching, conflict, preservation and validation tests passed');
