'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const Registration=require('../public/passenger-registration');
const source=fs.readFileSync(require.resolve('../public/app.js'),'utf8');
const slice=(from,to)=>source.slice(source.indexOf(from),source.indexOf(to,source.indexOf(from)));
const read=slice('    function readPassengers()', '    let passengerListSaving');
const sync=slice('    function syncPassengerRowPrice(', '    function ensurePassengerRows');
const price=slice('    function parseMoneyAmount(', '    function getPassengerContext');
const fields={listTourSelect:{value:'tour'},listTourId:{value:'tour'}};
const inputs={};for(const [,selector] of read.matchAll(/querySelector\('([^']+)'\)/g))inputs[selector]={value:''};
Object.assign(inputs,{'.p-name':{value:'Örnek Yolcu'},'.p-room-people':{value:'2'},'.p-custom-price':{value:'1450'},'.p-custom-currency':{value:'USD'}});
const paid={agreedPrice:1450,currency:'USD',priceSource:'room',payments:[{id:'existing-payment',amount:300,receiptNo:'ORNEK-001'}]};
const row={dataset:{passengerId:'person',priceSource:'room'},_accounting:structuredClone(paid),querySelector:selector=>inputs[selector]};
fields.passengerTable={querySelectorAll:()=>[row]};
const env={$:id=>fields[id],state:{tours:[{id:'tour',type:'umre',priceCurrency:'TRY',roomPrices:{'2':'1450 TRY'}}],passengerLists:[]},window:{TurizmPassengerRegistration:Registration},IS_APP_MODE:true,clone:structuredClone,uid:()=>{throw Error('Existing ID must be preserved');},currentActor:()=>({id:'owner'})};
vm.runInNewContext(price+sync+read,env);
env.syncPassengerRowPrice(row,true);
assert.equal(inputs['.p-custom-currency'].value,'USD','Changing a room/tour must keep currency when payment history exists');
let result=env.readPassengers()[0];assert.deepEqual(result.accounting.payments,paid.payments);assert.equal(result.accounting.currency,'USD');assert.equal(result.accounting.agreedPrice,1450);
inputs['.p-custom-currency'].value='TRY';assert.throws(()=>env.readPassengers(),/para birimi/,'Read path must reject reinterpretation of existing payments');
row._accounting={agreedPrice:'',currency:'',priceSource:'room',payments:[]};inputs['.p-custom-currency'].value='USD';inputs['.p-custom-price'].value='';env.syncPassengerRowPrice(row);
result=env.readPassengers()[0];assert.equal(result.accounting.currency,'TRY');assert.equal(result.accounting.agreedPrice,1450);
row.dataset.priceSource='custom';inputs['.p-custom-price'].value='980';inputs['.p-custom-currency'].value='EUR';env.syncPassengerRowPrice(row);
result=env.readPassengers()[0];assert.equal(result.accounting.currency,'EUR');assert.equal(result.accounting.agreedPrice,980);
console.log('Actual passenger pricing: tour currency inherited, custom agreement retained, existing payment currency/amount/history preserved and conflicting currency blocked.');
