const assert=require('node:assert/strict'),R=require('../public/passenger-registration'),P=require('../public/bus-plan');
const p=(id,name,extra={})=>({id,name,roomPeople:'2',...extra});
const item={id:'list',tourId:'tour',passengers:[p('a','Ayşe Örnek',{relationship:'Kendisi',roomGroup:'A',busNo:'1',seatNo:'5'}),p('b','Mehmet Başka',{relationship:'Eşi',relativePassengerId:'a',roomGroup:'A',busNo:'1',seatNo:'6'})]};
let plans=R.syncPlans({},[item],null,item);assert.equal(plans.tour.buses.length,1);assert.equal(plans.tour.buses[0].assignments[5],P.key('list','a'));assert.equal(plans.tour.buses[0].assignments[6],P.key('list','b'));
assert.equal(R.rooms(item.passengers)[0].occupants.length,2);assert.equal(R.rooms(item.passengers)[0].roomGroup,'A');assert.equal(P.roster([item],'tour')[0].group,P.roster([item],'tour')[1].group);
const before=JSON.stringify(plans),swap={...item,passengers:item.passengers.map((p,i)=>({...p,seatNo:i?'5':'6'}))};
plans=R.syncPlans(plans,[swap],item,swap);assert.equal(plans.tour.buses[0].assignments[6],P.key('list','a'));assert.equal(plans.tour.buses[0].assignments[5],P.key('list','b'));
const collision={id:'other',tourId:'tour',passengers:[p('c','Çakışan Yolcu',{busNo:'1',seatNo:'5'})]};assert.throws(()=>R.syncPlans(plans,[swap,collision],null,collision),/dolu/);assert.equal(JSON.stringify(R.syncPlans(JSON.parse(before),[item],item,item)),before);
assert.throws(()=>R.validate([p('x','Eksik',{busNo:'1'})]),/birlikte/);assert.throws(()=>R.validate([p('x','Hatalı',{busNo:'1.5',seatNo:'5'})]),/birlikte/);assert.throws(()=>R.validate([p('x','Hatalı',{roomGroup:'AA'})]),/A–Z/);
assert.throws(()=>R.syncPlans({},[{...collision,passengers:[p('c','Koltuk Yok',{busNo:'1',seatNo:'50'})]}],null,{...collision,passengers:[p('c','Koltuk Yok',{busNo:'1',seatNo:'50'})]}),/koltuk yok/);
const custom=P.renumber(P.makeBus(),{5:'105',6:'106'});const customItem={...collision,passengers:[p('c','Özel Koltuk',{busNo:'1',seatNo:'105'})]};assert.equal(R.syncPlans({tour:{buses:[custom]}},[customItem],null,customItem).tour.buses[0].assignments[5],P.key('other','c'));
const second={...collision,passengers:[p('c','İkinci Otobüs',{busNo:'2',seatNo:'8'})]};assert.equal(R.syncPlans({},[second],null,second).tour.buses[1].assignments[8],P.key('other','c'));
const missingTour={...item,tourId:''};assert.throws(()=>R.syncPlans({},[missingTour],null,missingTour),/tur seçin/);
const moved=P.move(plans.tour,[P.key('list','a')],'bus-1',20);assert.deepEqual(R.currentSeat(moved,'list',item.passengers[0]),{busNo:'1',seatNo:'20'});
assert.equal(R.rooms([p('a','A',{roomGroup:'A'}),p('b','B',{roomGroup:'B'}),p('c','C',{roomGroup:'A'})])[0].occupants.map(p=>p.id).join(','),'a,c');
assert.equal(R.rooms([p('a','A'),p('b','B'),p('c','C')]).length,2);
const unchanged={...swap,passengers:swap.passengers.map(p=>({...p,phone:'123'}))};assert.deepEqual(R.syncPlans(plans,[unchanged],swap,unchanged),plans);
const cleared={...swap,passengers:swap.passengers.map(p=>({...p,busNo:'',seatNo:''}))};assert.equal(Object.keys(R.syncPlans(plans,[cleared],swap,cleared).tour.buses[0].assignments).length,0);
const deleted={...swap,passengers:[swap.passengers[0]]};assert.equal(Object.keys(R.syncPlans(plans,[deleted],swap,deleted).tour.buses[0].assignments).length,1);
assert.throws(()=>R.validate([p('a','Çocuk',{relationship:'Oğlu'})]),/kimin/);
assert.throws(()=>R.validate([p('a','Çocuk',{relationship:'Oğlu',relativePassengerId:'a'})]),/başka/);
assert.throws(()=>R.validate([p('a','Çocuk',{relationship:'Oğlu',relativePassengerId:'deleted'})]),/başka/);
assert.equal(R.relationshipText(item.passengers[1],item.passengers),'Ayşe Örnek · Eşi');
assert.equal(R.relationshipText(item.passengers[1],[{...item.passengers[0],name:'Ayşe Yeni Soyadı'}]),'Ayşe Yeni Soyadı · Eşi');
assert.equal(R.tourCurrency({priceCurrency:'TRY',roomPrices:{'2':'1450 USD'}}),'TRY');
assert.equal(R.tourCurrency({roomPrices:{'2':'1450 USD'}}),'USD');
assert.equal(R.tourCurrency({type:'yurtici'}),'TRY');
assert.equal(R.tourCurrency({type:'umre'}),'USD');
assert.equal(R.tourCurrency({id:'tour',roomPrices:{'2':'1450'}},[{tourId:'tour',passengers:[{accounting:{currency:'EUR'}}]}]),'EUR');
assert.equal(R.priceText('1.450 USD','TRY'),'1.450 TRY');
assert.equal(R.priceText('Fiyat Sorunuz','TRY'),'Fiyat Sorunuz');
assert.equal(R.hasPayments({payments:[{amount:300,voided:true}]}),true);
assert.equal(R.hasPayments({payments:[]}),false);
console.log('Passenger relationships, letter groups, exact seats, swaps, duplicate protection, custom labels, legacy rooming and atomic plans passed.');
