const assert=require('node:assert/strict');
const fs=require('node:fs');
const render=require('../public/api/_site-pages.cjs');
const design=require('../public/umre-visuals');
const {sanitizePublicState}=require('../public/api/_supabase');
const snapshot=require('../public/api/_public-snapshot.json');
const copy=()=>JSON.parse(JSON.stringify(snapshot));
const state=copy();
const tour=state.tours.find(t=>t.slug==='19-ekim-2026-umresi');
tour.title='Güncel <Umre>';tour.roomPrices={'2':'1775 USD','3':'1725 USD','4':'1675 USD'};
tour.program='1. Gün — Güncel açıklama\n2. Gün — Yeni ziyaret planı';
tour.summary='Yeni program özeti';tour.detailBannerImage='/assets/new-custom-banner.jpg';
const html=render.pages.renderProgramPage(render.prepared(state),tour,render.origin);
for(const pattern of [/Güncel &lt;Umre&gt;/,/1775 USD/,/1675 USD/,/Güncel açıklama/,/new-custom-banner.jpg/,/seo-lightbox/,/hazirlik-genel/]) assert.match(html,pattern);
assert.doesNotMatch(html,/Program yükleniyor|program-page.js/);
for(const list of [render.template('index.html',state),render.local(state),render.prices(state)]){
  assert.equal((list.match(/tour-card site-tour-card/g)||[]).length,8);
  assert.match(list,/Yeni program özeti/);assert.match(list,/Kişi başı 1675 USD/);
  assert.match(list,/Ümraniye Ofisi/);
}
assert.equal(render.content('<h1 id="title">Eski</h1>','title','Yeni'),'<h1 id="title">Yeni</h1>');
const blog=render.template('merak-edilenler.html',state);
assert.match(blog,/<section[^>]+id="blogPageHero"[^>]+umre-makkah-sunrise.png/);
assert.equal((blog.match(/class="blog-card"/g)||[]).length,6);
assert.doesNotMatch(blog,/yayınlayabilirsiniz/);
const changed=copy();
changed.tours=changed.tours.map(t=>({...t,status:'completed'}));
assert.equal(render.pages.activeUmreTours(changed).length,0);
assert.doesNotMatch(render.pages.renderSitemap(changed,render.origin),/19-ekim-2026-umresi/);
changed.tours=[{...tour,status:'active',departureDate:'2000-01-01'},{...tour,status:'draft'},{...tour,status:'active',published:false}];
assert.equal(render.pages.activeUmreTours(changed).length,0);
const custom=design.tour({...tour,image:'/assets/new-custom-cover.jpg'});
assert.equal(custom.image,'/assets/new-custom-cover.jpg');
const sanitized=sanitizePublicState({...snapshot,siteTours:[tour],tours:[{title:'ACCOUNTING_SENTINEL'}],passengerLists:[{name:'PRIVATE_SENTINEL'}],settings:{...snapshot.settings,adminPassword:'SECRET_SENTINEL'}});
const publicHtml=render.template('index.html',sanitized);
assert.match(publicHtml,/<div class="hero-bg"><div class="hero-slide active"[^>]*><\/div><\/div>\s*<div class="hero-overlay"/);
assert.doesNotMatch(publicHtml,/ACCOUNTING_SENTINEL|PRIVATE_SENTINEL|SECRET_SENTINEL/);
const endpoint=fs.readFileSync('public/api/site-page.js','utf8');
assert.match(endpoint,/req.method!=='GET'/);
assert.doesNotMatch(endpoint,/\.upsert\(|\.insert\(|\.update\(|\.delete\(/);
assert.match(fs.readFileSync('public/admin.html','utf8'),/umre-visuals.js\?v=20260930-1/);
assert.match(fs.readFileSync('server.js','utf8'),/pathname === '\/api\/site-page'/);
const config=JSON.parse(fs.readFileSync('vercel.json','utf8'));
assert.equal(config.redirects.find(r=>r.source==='/tr/haberler').destination,'/merak-edilenler');
assert.equal(config.redirects.find(r=>r.source==='/tr/iletisim').destination,'/tr#iletisim');
assert.equal(config.redirects.find(r=>r.source==='/tr/hac-umre').destination,'/umre-fiyatlari');
console.log('Complete live first-paint HTML, shared cards, six articles/page, custom edits, archive filtering, and public-only read path passed');
