const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const path = require('node:path');
const root = path.join(__dirname, '..');
const context = { window: {} };
vm.runInNewContext(fs.readFileSync(path.join(root, 'public/umre-visuals.js'), 'utf8'), context);
const { umreVisual, umrePackage } = context.window;
assert.equal(umreVisual({slug:'19-ekim-2026-umresi'}, '/assets/gallery-medine.jpeg'), '/assets/umre-cover-19-ekim.png');
assert.equal(umreVisual({slug:'tam-ramazan-umresi-37-gun'}, '/assets/hotel.svg'), '/assets/umre-cover-tam-ramazan.png');
assert.equal(umreVisual({slug:'unrelated'}, '/assets/hotel.svg'), '/assets/hotel.svg');
assert.equal(umreVisual({slug:'19-ekim-2026-umresi'}, 'https://example.com/new.jpg'), 'https://example.com/new.jpg');
const tour = umrePackage({slug:'19-ekim-2026-umresi',included:[],excluded:[]});
assert.equal(tour.included.length, 7);
assert.ok(tour.included.includes('Kahvaltı ve akşam yemeği'));
assert.equal(tour.excluded.length, 3);
const custom = {slug:'19-ekim-2026-umresi',included:['Yeni kapsam'],excluded:['Yeni istisna']};
assert.equal(umrePackage(custom).included[0], 'Yeni kapsam');
for (const asset of ['umre-makkah-sunrise.png','umre-madinah-night.png','hazirlik-genel.png','hazirlik-erkek.png','hazirlik-kadin.png','hazirlik-harc.png']) assert.ok(fs.statSync(path.join(root,'public/assets',asset)).size > 1000);
console.log('Umrah presentation: targeted covers, future uploads, confirmed package scope and all six assets passed');
const slugs=['19-ekim-2026-umresi','6-kasim-2026-umresi','kasim-ara-tatil-umresi','14-aralik-2026-umresi','21-ocak-2027-umresi','tam-ramazan-umresi-37-gun','ramazan-medine-40-vakit-programi','son-15-ramazan-umresi'];
const covers=slugs.map(slug=>umreVisual({slug},''));
assert.equal(new Set(covers).size,8);
for(const cover of covers) assert.ok(fs.existsSync(path.join(root,'public',cover)));
const corrected=umrePackage({slug:slugs[0],included:[],excluded:[],mekkeImages:['https://pix10.agoda.net/0f2eedc7afedd733bfcf146f97fea881.jpeg']});
assert.equal(corrected.mekkeImages[0],'/assets/orooq-mahbes-entrance.jpg');
assert.ok(!fs.readFileSync(path.join(root,'public/program-page.js'),'utf8').includes('Kapak görseli yapay zekâ'));
console.log('Eight distinct covers, corrected Mahbes image and removed banner notice passed');
